spring:
  application:
    name: user-center
  profiles:
    active: dev
  # 数据库配置
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/ayasagiliowo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    password: CkW5fWvL1kg7mRN0
    username: ayasagiliowo
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
  servlet:
    context-path: /api
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: "default"
      paths-to-match: "/**"
      packages-to-scan: com.user
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

#mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml # 指定mapper文件位置
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名自动映射
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler # 枚举类型映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启mybatis日志
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑删除值
      logic-not-delete-value: 0 # 逻辑未删除值
      id-type: auto # 主键类型
      logic-delete-field: is_delete # 逻辑删除字段
